#include "stm32f469xx.h"
#include "stm32f4xx.h"
#include "timers.h"


unsigned int countWakeUp = 0;  // extern
int flagmsTicks = 0;  // extern

//******************************************************************************************************************************

// ***********************************************************************************************************************************

// TIM2 - 1 second for Trigger Output ADC injected channel (check internal sensors)
void TIM2_Init (void)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN; // Enable TIM2 Clock
	TIM2->PSC = 9000 - 1;    // Set Prescaler and Auto-reload for 1 second interval
	TIM2->ARR = 10000 - 1;
	// Choose the trigger event. Options for ADC Injected: To use TIM1_TRGO
	// MMS = 010: The update event is selected as trigger output
	TIM2->CR2 &= ~TIM_CR2_MMS; // Master mode selection. These bits allow to select the information to be sent in master mode to slave timers for synchronization (TRGO)
	TIM2->CR2 |= (0x2 << TIM_CR2_MMS_Pos);  // The update event is selected as trigger output (TRGO)
	TIM2->CR1 |= TIM_CR1_CEN; // Start Timer
}

/**
 * @brief Precise delay in microseconds using TIM2, max 65535µs (TIM7 16bit counter)
 * The timer is enabled and disabled dynamically to save power.
 * Timer 7 is a smart choice for a microsecond delay because it is a Basic Timer.
 */
void Delay_us_TIM7(uint16_t us)
{
	if (us == 0) return;
	RCC->APB1ENR |= RCC_APB1ENR_TIM7EN;  // 1. Enable TIM2 clock (TIM2 is on the APB1 bus)
	TIM7->PSC = 90 - 1;
	TIM7->ARR = us - 1;
	TIM7->CNT = 0;        // Reset counter
	TIM7->EGR |= TIM_EGR_UG;    // Force update to load PSC and ARR
	TIM7->SR &= ~TIM_SR_UIF;  // Clear the update flag generated by EGR
	TIM7->CR1 |= TIM_CR1_OPM | TIM_CR1_CEN; // Start the timer in One-Pulse Mode, OPM bit makes the timer stop automatically after the match
	while (TIM7->CR1 & TIM_CR1_CEN);  // Wait until the CEN bit is cleared by hardware
	TIM7->CR1 &= ~TIM_CR1_CEN;  // Cleanup: Stop timer
	RCC->APB1ENR &= ~RCC_APB1ENR_TIM7EN; // Disable the clock to save power (optional)
}


void TIM3config (uint16_t Timeout) //  one-pulse length for I2C Timeout
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // Enable TIM3 Clock (on APB1)
	TIM3->PSC = 900 - 1; //  Set Prescaler and Auto-reload -> 90MHz / 900 = 100kHz
	TIM3->ARR = Timeout - 1;
	TIM3->EGR |= TIM_EGR_UG; // (1U<<0); Send an update event to reset the timer and apply settings.
	TIM3->SR &= ~TIM_SR_UIF; // Clear Update Interrupt Flag (recommended before enabling)
	TIM3->DIER |= TIM_DIER_UIE; // Enable the hardware interrupt; (1U<<0); 1: Update interrupt enabled;
	TIM3->CR1 |= TIM_CR1_OPM; 	// Set One-Pulse Mode (bit set: Counter stops counting at the next update event (clearing the bit CEN))
	TIM3->SR = 0;
	NVIC_SetPriority(TIM3_IRQn, 2);
	NVIC_EnableIRQ(TIM3_IRQn); // basic ARM Cortex element defined in core_cm4.h
}

/* PWM output TIMER5 CH2 on PA1. The Prescaler (PSC) and Auto-Reload (ARR)
	The brightness "resolution" is defined by the ARR register. It is set it to 1000: your brightness variable works on a scale of 0 to 1000.
 In PWM Mode 1, the output is "High" as long as the counter (TIM5->CNT) is less than the Capture/Compare Register (TIM5->CCR2).
 Once the counter exceeds CCR2, the output drops "Low".
 */
void PWM_TIM5_Init(void) {
    // 1. Enable Clocks
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;   // Enable GPIOA clock
    RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;    // Enable TIM5 clock

    // 2. Configure PA1 as Alternate Function
    GPIOA->MODER &= ~(GPIO_MODER_MODER1);  // Clear bits
    GPIOA->MODER |= (GPIO_MODER_MODER1_1); // Set to Alternate Function (10)
    // Set Alternate Function to AF2 (TIM5) for PA1
    GPIOA->AFR[0] &= ~(0xF << (1 * 4));
    GPIOA->AFR[0] |= (0x2 << (1 * 4));     // AF2


    // 3. Configure TIM5 Timebase
    // Assuming 90MHz APB1 clock, this gives ~90Hz PWM frequency
    TIM5->PSC = 90 - 1;       // Prescaler: 1MHz clock to timer
    TIM5->ARR = 1000 - 1;     // Auto-reload: PWM period of 1000 steps
    // 4. Configure TIM5 Channel 2 for PWM Mode 1
    TIM5->CCMR1 &= ~(TIM_CCMR1_OC2M);      // Clear bits
    TIM5->CCMR1 |= (0x6 << TIM_CCMR1_OC2M_Pos); // PWM Mode 1 (110)
    TIM5->CCMR1 |= TIM_CCMR1_OC2PE;        // Enable Preload
    // 5. Enable Output and Start Timer
    TIM5->CCER |= TIM_CCER_CC2E;           // Enable Channel 2 output
    TIM5->CR1 |= TIM_CR1_CEN;              // Enable Counter

    // 6. Set initial Duty Cycle (50%)
    TIM5->CCR2 = 100;    // must store a value between 0 and ARR (999) into TIM5->CCR2
}


// config TIMER 6 periodic interrupts in ms
void TIM6_Init (uint16_t ms)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM6EN; // Enable TIMER6 as it is on the APB1 bus (1<<4);
	TIM6->PSC = 9000 - 1; //  ->  ; Prescaler (from APB1 90Mhz timer clocks) (for 1ms: psc = 90 & arr = 999)
	uint16_t arr = ms > 6550 ? 65500 : 10* ms; // check limit of TIM6->ARR with uint16_t max value
	TIM6->ARR = arr - 1; //  ->  ; The ARR determines the max value the timer will count to before it resets to 0
	TIM6->EGR |= TIM_EGR_UG; // (1U<<0); Send an update event to reset the timer and apply settings.
	TIM6->SR &= ~TIM_SR_UIF; // 3. Clear Update Interrupt Flag (recommended before enabling)
	TIM6->DIER |= TIM_DIER_UIE; // Enable the hardware interrupt; (1U<<0); 1: Update interrupt enabled;
	TIM6->SR = 0;
	NVIC_SetPriority(TIM6_DAC_IRQn, 10);
	NVIC_EnableIRQ(TIM6_DAC_IRQn);
	TIM6->CR1 |= TIM_CR1_CEN; // CEN: Counter enable (1<<0);
}


// config TIMER 8 - Encoder Mode - uses PC6 (TIM8_CH1) and PC7 (TIM8_CH2) as the encoder inputs.
void TIM8_Init (void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;    // Enable GPIOC clock
	RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;     // Enable TIM8 clock
	__DSB(); // Small delay after enabling clocks (recommended)
	GPIOC->MODER &= ~(GPIO_MODER_MODER6 | GPIO_MODER_MODER7); 	// Configure GPIO PC6 and PC7 as Alternate Function (clear all the bits at first)
	GPIOC->MODER |= (GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1); // Mode: 10 (AF)
    GPIOC->AFR[0] &= ~((0xFU << (6 * 4)) | (0xFU << (7 * 4)));
	GPIOC->AFR[0]  |= (3 << GPIO_AFRL_AFSEL6_Pos) | (3 << GPIO_AFRL_AFSEL7_Pos); 	// Set AF3 (TIM8) for PC6 and PC7
	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD6 | GPIO_PUPDR_PUPD7); // Pull: 01 (No Pull-up)
	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED6_Msk | GPIO_OSPEEDR_OSPEED7_Msk); // Speed: Low

	// Encoder Mode 3: This counts on every transition (rising and falling) of both Phase A and Phase B. This provides 4x the resolution of the physical "clicks" on most mechanical encoders.
	TIM8->SMCR &= ~TIM_SMCR_SMS;	// (clear all the bits at first)
	TIM8->SMCR |= (TIM_SMCR_SMS_0 | TIM_SMCR_SMS_1); // SMS = 011 (Encoder mode 3: counts on both TI1 and TI2 edges)

	TIM8->CCMR1 &= ~(TIM_CCMR1_CC1S | TIM_CCMR1_CC2S); // Configure channels as inputs (clear all the bits at first)
	TIM8->CCMR1 |= TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0;  // CC1S: Capture/Compare 1 selection - 01: with CC1 channel is configured as input, IC1 is mapped on TI1

	TIM8->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC1NP | TIM_CCER_CC2P | TIM_CCER_CC2NP); 	// Set Polarity (00 = non-inverted/rising edge)
	TIM8->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E; // determines if a capture of the counter value can actually be done into the input capture/compare register 1 (TIMx_CCR1) or not.

	TIM8->CCMR1 &= ~(TIM_CCMR1_IC1F | TIM_CCMR1_IC2F); // Input capture filter; defines the freq used to sample TI1 input and the length of the digital filter applied to TI1
	TIM8->CCMR1 |= (0x3 << TIM_CCMR1_IC1F_Pos) | (0x3 << TIM_CCMR1_IC2F_Pos);	// 0011: Sample at fCK_INT, N=8. This is usually sufficient for most mechanical encoders
	TIM8->CR1 &= ~TIM_CR1_CKD; 	// Encoder is still jittery ? you can increase the filter duration. The sampling freq can be divided down from the internal clock using the DTS (Dead-Time and Sampling) clock divider
	TIM8->PSC = 0; 		// No prescaler
	TIM8->ARR = 0xFFFF; 	// reload value at maximum
	TIM8->CNT = 0; // Clear counter
	//TIM8->DIER = TIM_DIER_TIE; 		// TIE: Trigger interrupt enable
	TIM8->DIER = TIM_DIER_UIE; 		// TIE: Update interrupt enable
	// In encoder mode, the UIF (Update Interrupt Flag) triggers when the CNT register reaches the ARR value (overflow) or 0 (underflow).
	// If you need an interrupt on every rising edge of the signal specifically, you should enable the Capture/Compare interrupt (CC1IE) and set the CC1S to input.
	TIM8->DIER |= TIM_DIER_CC1IE; // Interrupt on every transition of CH1 (optionnal)
	TIM8->DIER |= TIM_DIER_CC2IE; // Interrupt on every transition of CH2 (optionnal)
//	NVIC_SetPriority(TIM8_UP_TIM13_IRQn, 2);
//	NVIC_EnableIRQ(TIM8_UP_TIM13_IRQn);
	NVIC_SetPriority(TIM8_CC_IRQn, 12);
	NVIC_EnableIRQ(TIM8_CC_IRQn);
	//NVIC_SetPriority(TIM8_TRG_COM_TIM14_IRQn, 2);
	//NVIC_EnableIRQ(TIM8_TRG_COM_TIM14_IRQn);
	TIM8->CR1 |= TIM_CR1_CEN; 	// CEN: Counter enable;
}


// Records the starting tick count and waits until the required nb of ms has passed. It’s non-blocking, the CPU can still handle interrupts while waiting
void NBdelay_ms(uint32_t ms)
{
    uint32_t start = msTicks;
    while ((msTicks - start) < ms) {}
}


void RTC_WKUP_IRQHandler()
{
    EXTI->PR = (1U<<22);// This bit is set when the selected edge event arrives on the external interrupt line. This bit is cleared by programming it to ‘1’.
    if((RTC->ISR & RTC_ISR_WUTF)!=0) // (1U<<10 WUTF: this flag is set by hardware when the wakeup auto-reload counter reaches 0.
    {									// 1: Wakeup timer configuration update allowed
    	GPIOK->ODR ^= GPIO_ODR_OD3; //toggle PK3 (bleu)
    	RTC->ISR &= ~RTC_ISR_WUTF; // (0U<<10); this flag is cleared by software by writing 0
    	countWakeUp++;
    }
}
