
#include "timers.h"


unsigned int countWakeUp = 0;  // extern
int flagmsTicks = 0;  // extern

//******************************************************************************************************************************


/**
 * @brief Precise delay in microseconds using TIM2, max 65535µs (TIM7 16bit counter)
 * The timer is enabled and disabled dynamically to save power.
 * Timer 7 is a smart choice for a microsecond delay because it is a Basic Timer.
 */
void Delay_us_TIM7(uint16_t us)
{
	if (us == 0) return;
	RCC->APB1ENR |= RCC_APB1ENR_TIM7EN;  // 1. Enable TIM2 clock (TIM2 is on the APB1 bus)
	TIM7->PSC = 90 - 1;
	TIM7->ARR = us - 1;
	TIM7->CNT = 0;        // Reset counter
	TIM7->EGR |= TIM_EGR_UG;    // Force update to load PSC and ARR
	TIM7->SR &= ~TIM_SR_UIF;  // Clear the update flag generated by EGR
	TIM7->CR1 |= TIM_CR1_OPM | TIM_CR1_CEN; // Start the timer in One-Pulse Mode, OPM bit makes the timer stop automatically after the match
	while (TIM7->CR1 & TIM_CR1_CEN);  // Wait until the CEN bit is cleared by hardware
	TIM7->CR1 &= ~TIM_CR1_CEN;  // Cleanup: Stop timer
	RCC->APB1ENR &= ~RCC_APB1ENR_TIM7EN; // Disable the clock to save power (optional)
}


// Records the starting tick count and waits until the required nb of ms has passed. It’s non-blocking, the CPU can still handle interrupts while waiting
void NBdelay_ms(uint32_t ms)
{
    uint32_t start = msTicks;
    while ((msTicks - start) < ms) {}
}


void RTC_WKUP_IRQHandler()
{
    EXTI->PR = (1U<<22);// This bit is set when the selected edge event arrives on the external interrupt line. This bit is cleared by programming it to ‘1’.
    if((RTC->ISR & RTC_ISR_WUTF)!=0) // (1U<<10 WUTF: this flag is set by hardware when the wakeup auto-reload counter reaches 0.
    {									// 1: Wakeup timer configuration update allowed
    	GPIOK->ODR ^= GPIO_ODR_OD3; //toggle PK3 (bleu)
    	RTC->ISR &= ~RTC_ISR_WUTF; // (0U<<10); this flag is cleared by software by writing 0
    	countWakeUp++;
    }
}
